site_name: qngplex Documentation
repo_url: https://github.com/tsileo/qngplex/
dev_addr: 0.0.0.0:8000
theme: yeti
pages:
  - [index.md, Home]
  - [HACKING.md, Hacking]
  - [DESIGN.md, Design]
  - [api_rest.md, API, REST API]
  - [api_query.md, API, Query API]
  - [api_sse.md, API, Server-Sent Events API]
